-- SQL à exécuter dans le SQL Editor de Supabase pour activer les nouvelles fonctionnalités

-- 1. Support de l'archivage et de la détection de dossiers incomplets
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT false;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS incomplete_reason TEXT;

-- 2. Table pour le journal d'audit (Suivi des actions admin)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_email TEXT,
    action TEXT, -- 'CREATE', 'UPDATE', 'ARCHIVE', 'IMPORT'
    target_id TEXT,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
