const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
const { createClient } = require('@supabase/supabase-js');
const XLSX = require('xlsx');
const { calculateRetirementDate } = require('./utils/retirement');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('CRITICAL ERROR: Supabase Environment Variables are missing.');
    console.error('Please configure SUPABASE_URL and SUPABASE_ANON_KEY in your Vercel Project Settings.');
    throw new Error('Missing Supabase Environment Variables');
}

const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * Note: Dans Supabase, la table doit être créée via le tableau de bord ou un script SQL.
 * SQL à exécuter dans le SQL Editor de Supabase :
 * 
 * CREATE TABLE teachers (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   matricule TEXT,
 *   nom TEXT,
 *   prenoms TEXT,
 *   sexe TEXT,
 *   date_naissance TEXT,
 *   lieu_naissance TEXT,
 *   statut TEXT,
 *   corps TEXT,
 *   grade TEXT,
 *   etablissement TEXT,
 *   commune TEXT,
 *   fonction TEXT,
 *   discipline TEXT,
 *   date_prise_service TEXT,
 *   date_retraite DATE,
 *   is_college BOOLEAN,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 */

async function importExcel(excelPath) {
    const workbook = XLSX.readFile(excelPath);
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const data = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

    const FEMININE_NAMES = [
        'MARIE', 'ROSE', 'GRACE', 'IRENE', 'DIANE', 'MONIQUE', 'CLARISSE', 'VANESSA',
        'THERESE', 'YVETTE', 'ELISE', 'COLETTE', 'GEORGETTE', 'BERNADETTE', 'ANTOINETTE',
        'ANGELE', 'ALICE', 'AMINATA', 'FATOUMATA', 'AWA', 'RAMATOU', 'ZAINAB', 'SOLANGE',
        'ESTHER', 'LUCIE', 'FLORENCE', 'ADELAIDE', 'CHARLOTTE', 'MARGUERITE', 'RACHEL',
        'REBECCA', 'SARAH', 'LEA', 'NOELIE', 'JULIE', 'JUSTINE', 'SYLVIE', 'MARTINE',
        'ISABELLE', 'NATHALIE', 'VALERIE', 'PASCALINE', 'CLOTILDE', 'GENEVIEVE', 'HELENE',
        'MADELEINE', 'VICTORINE', 'JEANNE', 'PAULETTE', 'ODETTE', 'FRANCOISE', 'CATHERINE',
        'ANNE', 'SOPHIE', 'CHANTAL', 'BEATRICE', 'VERONIQUE', 'DOMINIQUE', 'MURIEL', 'BRIGITTE'
    ];
    const FEMININE_ENDINGS = ['ETTE', 'INE', 'ELLE', 'ENCE', 'ANTE', 'ANNE', 'IE', 'ISE', 'A', 'AH'];

    const teachersData = data.slice(1).map(row => {
        if (!row[1]) return null;

        const birthDateValue = row[4];
        const establishment = row[9];
        const grade = row[8];
        const prenoms = (row[2] || '').toUpperCase();
        let sexe = (row[3] || 'M').toString().toUpperCase();

        // Heuristic detection if sexe is 'M' but name is feminine
        if (sexe === 'M') {
            const firstPrenom = prenoms.split(' ')[0].split('-')[0];
            if (FEMININE_NAMES.some(name => prenoms.includes(name)) ||
                FEMININE_ENDINGS.some(ending => firstPrenom.endsWith(ending))) {
                sexe = 'F';
            }
        }

        const retirementDate = calculateRetirementDate(birthDateValue, grade, establishment);
        const retirementDateStr = retirementDate ? retirementDate.toISOString().split('T')[0] : null;
        const isCollege = establishment && establishment.toUpperCase().startsWith('CEG');

        return {
            matricule: row[0] ? row[0].toString() : '',
            nom: row[1],
            prenoms: row[2],
            sexe: sexe,
            date_naissance: birthDateValue ? birthDateValue.toString() : '',
            lieu_naissance: row[5],
            statut: row[6],
            corps: row[7],
            grade: row[8],
            etablissement: row[9],
            commune: row[10],
            fonction: row[11],
            discipline: row[12],
            date_prise_service: row[13] ? row[13].toString() : '',
            date_retraite: retirementDateStr,
            is_college: isCollege ? true : false
        };
    }).filter(t => t !== null);

    // Insertion par lots (Supabase gère bien les batchs)
    const { data: insertedData, error } = await supabase
        .from('teachers')
        .insert(teachersData);

    if (error) {
        console.error('Erreur Supabase Import:', error);
        throw error;
    }
    console.log(`${teachersData.length} enseignants importés sur Supabase.`);
}

module.exports = { supabase, importExcel };
